services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 50501:50501
      - 50601:50601/udp
      - 50701:50701
      # bluemap webserver
    environment:
      MODPACK_PLATFORM: MODRINTH
      MODRINTH_MODPACK: /modpacks/1.21.1 server instance 0.0.8c.mrpack
      EULA: "TRUE"
      MEMORY: 8G
      RCON_PASSWORD: [REDACTED]
      MOTD: temple's custom NeoForge server
      OPS: TempleOfShadows
      MODRINTH_PROJECTS: |
        bluemap:Hp4CqBgz
      # Distant Horizons has a server file on the way.
      MODRINTH_EXCLUDE_FILES: | 
        distanthorizons 
      SERVER_PORT: 50501
      WHITELIST_FILE: https://github.com/templeofshadow/mc-server-fileshare/raw/refs/heads/main/modrinth%20modpack%20backup/whitelist.json
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./modpacks:/modpacks:ro
  restore-backup:
    # Same image as mc, but any base image with bash and tar will work
    image: itzg/mc-backup
    user: "1000"
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as mc service, needs to be writable
      - ./data:/data
      - /storage/storage-1/mc-backups/minecraftjava/backups:/backups:ro
  backups:
    image: itzg/mc-backup
    user: "1000"
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: 12h
      PRUNE_BACKUPS_DAYS: 5
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
      # As an example, to backup only the world data:
      # INCLUDES: world,world_nether,world_the_end
    volumes:
      - ./data:/data:ro
      - /storage/storage-1/mc-backups/minecraftjava/backups:/backups
networks: {}
